# Generated by Django 5.1.3 on 2024-11-13 10:07

import capital_calls.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('iban', models.CharField(max_length=34, validators=[capital_calls.models.validate_iban])),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_calls', to='capital_calls.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('membership', 'Membership'), ('upfront', 'Upfront Fee'), ('yearly', 'Yearly Fee')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('due_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('fee_percentage', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=5, validators=[capital_calls.models.validate_fee_percentage])),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='capital_calls.investor')),
            ],
        ),
    ]
